### ISSUE TITLE
7 major vulnerabilities

### ISSUE THREAD

**Issue by missulmer** [descope-sample-apps/b2b-react-sample-app#7]
When running npm I the audit returns issues.

_although the project may still run fine with these issues, that isn't the core issue_

If I attempt to update your project, I  could break it.

**Why it matters:**
As an influencer buying decision, I am noting that you are offering sample projects that are not maintained.
This could be viewed as a strike against adoption of the commercial grade product because it implies the risk that your practices on the commercial grade product may be weak.
When I am evaluating an auth provider I look for signs like this.

--> Recommendation --->
Limit your sample apps to a ‘certified’ set and hold them at the same quality bar you hold your commercial-grade product offering.  At a minium fix your b2b and b2c projects that you offer to people evaluating your auth solution.

**Zoom In
w3c-hr-time**: The package is deprecated because modern JavaScript platforms natively support performance.now() and performance.timeOrigin. You should replace the use of this package with the native methods.
svgo: Version 1.3.2 of SVGO is no longer supported. You should upgrade to version 2.x.x to continue receiving updates and bug fixes.
stable: Modern JavaScript guarantees that Array#sort() is a stable sort, making this library unnecessary. You can remove this package and use the native Array#sort() method.
sourcemap-codec: This package is deprecated and replaced by the @jridgewell/sourcemap-codec package. You should update your project to use the new package.
rollup-plugin-terser: This package is deprecated and no longer maintained. You should replace it with the @rollup/plugin-terser package.

---
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser

**Comment by gshriki** [comment]
@missulmer, thanks for the feedback. We have added e2e tests and enabled auto upgrades in this repo, and will add to all other sample apps repos.
